/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SurfacesRouteImport } from './routes/surfaces'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchemasRouteImport } from './routes/schemas'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as EndpointsRouteImport } from './routes/endpoints'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValidatorsIndexRouteImport } from './routes/validators.index'
import { Route as SudoIndexRouteImport } from './routes/sudo.index'
import { Route as SubnetsIndexRouteImport } from './routes/subnets.index'
import { Route as RuntimeIndexRouteImport } from './routes/runtime.index'
import { Route as ProvidersIndexRouteImport } from './routes/providers.index'
import { Route as ExtrinsicsIndexRouteImport } from './routes/extrinsics.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as BlocksIndexRouteImport } from './routes/blocks.index'
import { Route as AdminChangesIndexRouteImport } from './routes/admin-changes.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as ValidatorsHotkeyRouteImport } from './routes/validators.$hotkey'
import { Route as ToolsSs58RouteImport } from './routes/tools.ss58'
import { Route as SubnetsNetuidRouteImport } from './routes/subnets.$netuid'
import { Route as ProvidersSlugRouteImport } from './routes/providers.$slug'
import { Route as GraphqlExplorerRouteImport } from './routes/graphql.explorer'
import { Route as ExtrinsicsHashRouteImport } from './routes/extrinsics.$hash'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs.llms[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs.$'
import { Route as BlocksRefRouteImport } from './routes/blocks.$ref'
import { Route as ApiSearchRouteImport } from './routes/api.search'
import { Route as AccountsSs58RouteImport } from './routes/accounts.$ss58'
import { Route as DocsRawSplatRouteImport } from './routes/docs.raw.$'

const SurfacesRoute = SurfacesRouteImport.update({
  id: '/surfaces',
  path: '/surfaces',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemasRoute = SchemasRouteImport.update({
  id: '/schemas',
  path: '/schemas',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointsRoute = EndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsIndexRoute = ValidatorsIndexRouteImport.update({
  id: '/validators/',
  path: '/validators/',
  getParentRoute: () => rootRouteImport,
} as any)
const SudoIndexRoute = SudoIndexRouteImport.update({
  id: '/sudo/',
  path: '/sudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsIndexRoute = SubnetsIndexRouteImport.update({
  id: '/subnets/',
  path: '/subnets/',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeIndexRoute = RuntimeIndexRouteImport.update({
  id: '/runtime/',
  path: '/runtime/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsIndexRoute = ExtrinsicsIndexRouteImport.update({
  id: '/extrinsics/',
  path: '/extrinsics/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksIndexRoute = BlocksIndexRouteImport.update({
  id: '/blocks/',
  path: '/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangesIndexRoute = AdminChangesIndexRouteImport.update({
  id: '/admin-changes/',
  path: '/admin-changes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidatorsHotkeyRoute = ValidatorsHotkeyRouteImport.update({
  id: '/validators/$hotkey',
  path: '/validators/$hotkey',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSs58Route = ToolsSs58RouteImport.update({
  id: '/tools/ss58',
  path: '/tools/ss58',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetsNetuidRoute = SubnetsNetuidRouteImport.update({
  id: '/subnets/$netuid',
  path: '/subnets/$netuid',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersSlugRoute = ProvidersSlugRouteImport.update({
  id: '/providers/$slug',
  path: '/providers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphqlExplorerRoute = GraphqlExplorerRouteImport.update({
  id: '/graphql/explorer',
  path: '/graphql/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtrinsicsHashRoute = ExtrinsicsHashRouteImport.update({
  id: '/extrinsics/$hash',
  path: '/extrinsics/$hash',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlocksRefRoute = BlocksRefRouteImport.update({
  id: '/blocks/$ref',
  path: '/blocks/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsSs58Route = AccountsSs58RouteImport.update({
  id: '/accounts/$ss58',
  path: '/accounts/$ss58',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRawSplatRoute = DocsRawSplatRouteImport.update({
  id: '/docs/raw/$',
  path: '/docs/raw/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runtime/': typeof RuntimeIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts': typeof AccountsIndexRoute
  '/admin-changes': typeof AdminChangesIndexRoute
  '/blocks': typeof BlocksIndexRoute
  '/events': typeof EventsIndexRoute
  '/extrinsics': typeof ExtrinsicsIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/runtime': typeof RuntimeIndexRoute
  '/subnets': typeof SubnetsIndexRoute
  '/sudo': typeof SudoIndexRoute
  '/validators': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agents': typeof AgentsRoute
  '/domains': typeof DomainsRoute
  '/endpoints': typeof EndpointsRoute
  '/explorer': typeof ExplorerRoute
  '/gaps': typeof GapsRoute
  '/health': typeof HealthRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/portfolio': typeof PortfolioRoute
  '/schemas': typeof SchemasRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/surfaces': typeof SurfacesRoute
  '/accounts/$ss58': typeof AccountsSs58Route
  '/api/search': typeof ApiSearchRoute
  '/blocks/$ref': typeof BlocksRefRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/extrinsics/$hash': typeof ExtrinsicsHashRoute
  '/graphql/explorer': typeof GraphqlExplorerRoute
  '/providers/$slug': typeof ProvidersSlugRoute
  '/subnets/$netuid': typeof SubnetsNetuidRoute
  '/tools/ss58': typeof ToolsSs58Route
  '/validators/$hotkey': typeof ValidatorsHotkeyRoute
  '/accounts/': typeof AccountsIndexRoute
  '/admin-changes/': typeof AdminChangesIndexRoute
  '/blocks/': typeof BlocksIndexRoute
  '/events/': typeof EventsIndexRoute
  '/extrinsics/': typeof ExtrinsicsIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/runtime/': typeof RuntimeIndexRoute
  '/subnets/': typeof SubnetsIndexRoute
  '/sudo/': typeof SudoIndexRoute
  '/validators/': typeof ValidatorsIndexRoute
  '/docs/raw/$': typeof DocsRawSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agents'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/blocks/$ref'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts/'
    | '/admin-changes/'
    | '/blocks/'
    | '/events/'
    | '/extrinsics/'
    | '/providers/'
    | '/runtime/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
    | '/docs/raw/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agents'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/blocks/$ref'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts'
    | '/admin-changes'
    | '/blocks'
    | '/events'
    | '/extrinsics'
    | '/providers'
    | '/runtime'
    | '/subnets'
    | '/sudo'
    | '/validators'
    | '/docs/raw/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agents'
    | '/domains'
    | '/endpoints'
    | '/explorer'
    | '/gaps'
    | '/health'
    | '/leaderboards'
    | '/portfolio'
    | '/schemas'
    | '/settings'
    | '/status'
    | '/surfaces'
    | '/accounts/$ss58'
    | '/api/search'
    | '/blocks/$ref'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/extrinsics/$hash'
    | '/graphql/explorer'
    | '/providers/$slug'
    | '/subnets/$netuid'
    | '/tools/ss58'
    | '/validators/$hotkey'
    | '/accounts/'
    | '/admin-changes/'
    | '/blocks/'
    | '/events/'
    | '/extrinsics/'
    | '/providers/'
    | '/runtime/'
    | '/subnets/'
    | '/sudo/'
    | '/validators/'
    | '/docs/raw/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgentsRoute: typeof AgentsRoute
  DomainsRoute: typeof DomainsRoute
  EndpointsRoute: typeof EndpointsRoute
  ExplorerRoute: typeof ExplorerRoute
  GapsRoute: typeof GapsRoute
  HealthRoute: typeof HealthRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  PortfolioRoute: typeof PortfolioRoute
  SchemasRoute: typeof SchemasRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SurfacesRoute: typeof SurfacesRoute
  AccountsSs58Route: typeof AccountsSs58Route
  ApiSearchRoute: typeof ApiSearchRoute
  BlocksRefRoute: typeof BlocksRefRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  ExtrinsicsHashRoute: typeof ExtrinsicsHashRoute
  GraphqlExplorerRoute: typeof GraphqlExplorerRoute
  ProvidersSlugRoute: typeof ProvidersSlugRoute
  SubnetsNetuidRoute: typeof SubnetsNetuidRoute
  ToolsSs58Route: typeof ToolsSs58Route
  ValidatorsHotkeyRoute: typeof ValidatorsHotkeyRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
  AdminChangesIndexRoute: typeof AdminChangesIndexRoute
  BlocksIndexRoute: typeof BlocksIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ExtrinsicsIndexRoute: typeof ExtrinsicsIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  RuntimeIndexRoute: typeof RuntimeIndexRoute
  SubnetsIndexRoute: typeof SubnetsIndexRoute
  SudoIndexRoute: typeof SudoIndexRoute
  ValidatorsIndexRoute: typeof ValidatorsIndexRoute
  DocsRawSplatRoute: typeof DocsRawSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/surfaces': {
      id: '/surfaces'
      path: '/surfaces'
      fullPath: '/surfaces'
      preLoaderRoute: typeof SurfacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemas': {
      id: '/schemas'
      path: '/schemas'
      fullPath: '/schemas'
      preLoaderRoute: typeof SchemasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoints': {
      id: '/endpoints'
      path: '/endpoints'
      fullPath: '/endpoints'
      preLoaderRoute: typeof EndpointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/': {
      id: '/validators/'
      path: '/validators'
      fullPath: '/validators/'
      preLoaderRoute: typeof ValidatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sudo/': {
      id: '/sudo/'
      path: '/sudo'
      fullPath: '/sudo/'
      preLoaderRoute: typeof SudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/': {
      id: '/subnets/'
      path: '/subnets'
      fullPath: '/subnets/'
      preLoaderRoute: typeof SubnetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime/': {
      id: '/runtime/'
      path: '/runtime'
      fullPath: '/runtime/'
      preLoaderRoute: typeof RuntimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/': {
      id: '/extrinsics/'
      path: '/extrinsics'
      fullPath: '/extrinsics/'
      preLoaderRoute: typeof ExtrinsicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/': {
      id: '/blocks/'
      path: '/blocks'
      fullPath: '/blocks/'
      preLoaderRoute: typeof BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-changes/': {
      id: '/admin-changes/'
      path: '/admin-changes'
      fullPath: '/admin-changes/'
      preLoaderRoute: typeof AdminChangesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validators/$hotkey': {
      id: '/validators/$hotkey'
      path: '/validators/$hotkey'
      fullPath: '/validators/$hotkey'
      preLoaderRoute: typeof ValidatorsHotkeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ss58': {
      id: '/tools/ss58'
      path: '/tools/ss58'
      fullPath: '/tools/ss58'
      preLoaderRoute: typeof ToolsSs58RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnets/$netuid': {
      id: '/subnets/$netuid'
      path: '/subnets/$netuid'
      fullPath: '/subnets/$netuid'
      preLoaderRoute: typeof SubnetsNetuidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$slug': {
      id: '/providers/$slug'
      path: '/providers/$slug'
      fullPath: '/providers/$slug'
      preLoaderRoute: typeof ProvidersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphql/explorer': {
      id: '/graphql/explorer'
      path: '/graphql/explorer'
      fullPath: '/graphql/explorer'
      preLoaderRoute: typeof GraphqlExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extrinsics/$hash': {
      id: '/extrinsics/$hash'
      path: '/extrinsics/$hash'
      fullPath: '/extrinsics/$hash'
      preLoaderRoute: typeof ExtrinsicsHashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocks/$ref': {
      id: '/blocks/$ref'
      path: '/blocks/$ref'
      fullPath: '/blocks/$ref'
      preLoaderRoute: typeof BlocksRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$ss58': {
      id: '/accounts/$ss58'
      path: '/accounts/$ss58'
      fullPath: '/accounts/$ss58'
      preLoaderRoute: typeof AccountsSs58RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/raw/$': {
      id: '/docs/raw/$'
      path: '/docs/raw/$'
      fullPath: '/docs/raw/$'
      preLoaderRoute: typeof DocsRawSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgentsRoute: AgentsRoute,
  DomainsRoute: DomainsRoute,
  EndpointsRoute: EndpointsRoute,
  ExplorerRoute: ExplorerRoute,
  GapsRoute: GapsRoute,
  HealthRoute: HealthRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  PortfolioRoute: PortfolioRoute,
  SchemasRoute: SchemasRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SurfacesRoute: SurfacesRoute,
  AccountsSs58Route: AccountsSs58Route,
  ApiSearchRoute: ApiSearchRoute,
  BlocksRefRoute: BlocksRefRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  ExtrinsicsHashRoute: ExtrinsicsHashRoute,
  GraphqlExplorerRoute: GraphqlExplorerRoute,
  ProvidersSlugRoute: ProvidersSlugRoute,
  SubnetsNetuidRoute: SubnetsNetuidRoute,
  ToolsSs58Route: ToolsSs58Route,
  ValidatorsHotkeyRoute: ValidatorsHotkeyRoute,
  AccountsIndexRoute: AccountsIndexRoute,
  AdminChangesIndexRoute: AdminChangesIndexRoute,
  BlocksIndexRoute: BlocksIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ExtrinsicsIndexRoute: ExtrinsicsIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  RuntimeIndexRoute: RuntimeIndexRoute,
  SubnetsIndexRoute: SubnetsIndexRoute,
  SudoIndexRoute: SudoIndexRoute,
  ValidatorsIndexRoute: ValidatorsIndexRoute,
  DocsRawSplatRoute: DocsRawSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
