/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.data.jsonc --include-runtime=false workers/data-api.worker-configuration.d.ts` (hash: 36869e8a0ba5d0c2c0e0c375a21a5a8a)
interface __BaseEnv_Env {
	METAGRAPH_CONTROL: KVNamespace;
	HYPERDRIVE: Hyperdrive;
	ALERT_TRIGGER_CREATE_RATE_LIMITER: RateLimit;
	WALLET_AUTH_RATE_LIMITER: RateLimit;
	ACCOUNT_KEYS_MINT_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	UNKEY_API_ID: "api_2Dv8cVjrTSiD";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./data-api.sentry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "UNKEY_API_ID">> {}
}
