/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.registry.jsonc --include-runtime=false workers/registry-sync-api.worker-configuration.d.ts` (hash: 5f6ea0528f71cc75a39e6c3d0c6517fe)
interface __BaseEnv_Env {
	HYPERDRIVE: Hyperdrive;
	REGISTRY_SYNC_RATE_LIMITER: RateLimit;
	CF_VERSION_METADATA: WorkerVersionMetadata;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./registry-sync-api.sentry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
